# Generated by Django 4.2.4 on 2023-09-06 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='category',
            field=models.CharField(default='Building', max_length=50),
        ),
        migrations.AddField(
            model_name='realestate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
