# Generated by Django 4.1.8 on 2024-03-09 23:30

from django.db import migrations, models
import here.models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='here/'),
        ),
        migrations.AlterField(
            model_name='realestateimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestateimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestateimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestateimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestateimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestateimage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
    ]
