# Generated by Django 4.2.4 on 2023-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0003_alter_user_client_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='images',
        ),
        migrations.RemoveField(
            model_name='realestateimage',
            name='description',
        ),
        migrations.AddField(
            model_name='realestate',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='here/images'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='here/images'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='here/images'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='here/images'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='here/images'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='here/images'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='here/videos'),
        ),
    ]
