# Generated by Django 4.1.8 on 2024-03-10 00:10

from django.db import migrations, models
import here.models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0003_alter_realestate_image1_alter_realestateimage_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to=here.models.upload_image_to),
        ),
    ]
