# Generated by Django 4.2.4 on 2023-09-12 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0004_remove_realestate_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='RealEstateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('apartment', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_meeting_scheduled', models.BooleanField(default=False)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('agreement_made', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
