# Generated by Django 4.2.4 on 2023-09-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0006_charge_subscription_alter_realestate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
