# Generated by Django 4.2.4 on 2023-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0007_alter_subscription_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='bundle',
            field=models.CharField(default='basic', max_length=50),
        ),
    ]
