# Generated by Django 4.2.4 on 2023-09-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0008_subscription_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatebooking',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='here.realestate'),
        ),
    ]
