# Generated by Django 4.2.4 on 2023-10-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0009_alter_realestatebooking_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
